test: &default

  # Credentials for REST APIs
  client_id: <%= Figaro.env.paypal_client_id %>
  client_secret: <%= Figaro.env.paypal_client_secret %>

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: <%= Figaro.env.paypal_app_id %>
  username: <%= Figaro.env.paypal_username %>
  password: <%= Figaro.env.paypal_password %>
  signature: <%= Figaro.env.paypal_signature %>
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: <%= Figaro.env.paypal_email_address %>

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: sandbox
