# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39e029f4832d9c1ce888e85f33810fbe05645827b9a69f83277d8b13304361364adeb1a8cdaf95cf710399e35904013f1955a70fed2a2e1b77943e8eff321252

test:
  secret_key_base: b90d5823854abfefe87688e0adacaeb0a33efe5e0dd22bb2d710d0d77d90367bd0fc1da9e4b5e3d9a3fa9f5701c18078cfa36c3bbaf16b93000f25214d952c99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
